---
include:
  - "mygame/app/**/*.rb"
  - "mygame/lib/**/*.rb"

exclude:
  - "mygame/repl.rb"
  - "**/dragonruby/**/*"
  - ".dragonruby/**/*"
  - "samples/**/*"
  - "docs/**/*"
  - "logs/**/*"
  - "tmp/**/*"
  - "builds/**/*"

require: []
domains: []
reporters:
  - rubocop
  - require_not_found
format: false
max_files: 1000
